### PR TITLE
Fix: Code is modifying constant object in store.ts

### PR DESCRIPTION
**Pull request by wotmshuaisi**

### CODE REVIEW

**Comment by Dreamacro** [comment]
I made the mistake of looking at the pre-modification and post-modification backward. This pr should not be merged. `const` in js is different from rust and other languages. It should be `const` instead of `let`

**Comment by wotmshuaisi** [comment]
[You've made your point. ](https://www.typescriptlang.org/docs/handbook/variable-declarations.html#const-declarations) How we going to solve this error? It doesn't look you've set read-only properties in Connection object.

```javascript
Uncaught TypeError: Cannot assign to read only property 'completed' of object '#<Object>'
    at Store.appendToSet (store.ts:43)
    at store.ts:90
    at EventEmitter.handleConnection (index.tsx:157)
    at EventEmitter.emit (index.js:181)
    at WebSocket.<anonymous> (streamer.ts:42)
```

**Comment by Dreamacro** [comment]
@wotmshuaisi What can I do to reproduce this error?

**Comment by Dreamacro** [comment]
c21d993 fixed

**Pull request merged**
