### PR TITLE
Feature: Add sorting for download speed column

### PR DESCRIPTION
**Pull request by AmagiDDmxh**
Sorting in connections table page are incomplete, there is a scenario trying to sort connections by download speed.

### CODE REVIEW

**Comment by Dreamacro** [comment]
refactored the way react-table was incorrectly used before, as the react-table was not well-supported in typescript, so it took some extra time to patch some of the types.

If you have anything to add to this change, you can make an additional patch on this PR

**Comment by AmagiDDmxh** [comment]
Ok, sounds great

**Comment by Dreamacro** [comment]
checkout the master for the refactor code

**Comment by AmagiDDmxh** [comment]
Wow, thats exactly what I plan to do the next few days, might not elegant as yours, but inherent quite the same procoess by making the data raw and format the display with renderCell. And thats pretty well done, thank you Dreamacro! Hope I can help in the near future.

**Comment by Dreamacro** [comment]
Close this PR for now.

**Pull request closed without merging**
