### PR TITLE
Fix CORS error in https dashboard with http api

### PR DESCRIPTION
**Pull request by proletarius101**
- Fix CORS error in https dashboard with http api
- Use `password` input type for `secret` field for better detection by password manager

### CODE REVIEW

**Comment by Dreamacro** [comment]
http://clash.razord.top
https://clash.razord.top

**Comment by proletarius101** [comment]
Sorry, is there anything wrong? It's not related to cross site in fact, just the error message says about CORS. The point is, we shouldn't pressume the protocol to access the dashboard is the same as the protocol to the REST api. Probably REST api runs at 127.0.0.1 with http, whereas the dashboard is host on the internet. If we limit the usage, most users will have to access the insecure http version which could easily be manipulated on transmission.

**Comment by Dreamacro** [comment]
If the website uses HTTPS but API use HTTP, it's insecure too. (aka [mixed-content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content?hl=zh-cn) )

**Comment by xcffl** [comment]
In that case, it's insecure because API access is insecure, not the dashboard access. It's more secure than the current arrangement, let alone the api is at localhost.

**Comment by proletarius101** [comment]
Bascially the aim is to be as secure as possible. The insecure characteristic is led by and limited to the insecure http content. Currently clash doesn't provide any method to host a  https api endpoint (to my knowledge, maybe there is but I can't think of a clean way to do so). The possible and most secure way is to allow mixed content.

**Comment by Dreamacro** [comment]
@proletarius101 For personal user, caddy provider automatic HTTPS https://caddyserver.com/docs/automatic-https .

BTW, the HTTPS dashboard doesn't make API secured. If you want to serve entirely locally, you can download the artifact on gh-pages, and use `external-ui` config

**Comment by proletarius101** [comment]
It's too much for a non-technical user to run a caddy server, or download and copy files to an appropriate directory. Of course the apriori is that average people are Clash's target audience as well.

Moreover, the API is always on the client side rather than the server side.  So it's the user that runs the clash client and the API. Dashboard could be served on another computer (via the internet) or locally. It's not that necessary to encrypt the transmission if you both serve and consume the API locally.

**Comment by Dreamacro** [comment]
@proletarius101 
Chrome and Firefox would block `Mixed Content` request when dashboard over HTTPS (localhost and 127.0.0.1 are special).

**Comment by proletarius101** [comment]
I'm totally aware of that. 127.0.0.1 is whitelisted to my knowledge, for the same reason as I said - it makes no difference if you encrypt and decrypt immidiately, unless the encrypt end and the decrypt end are isolated.

My point here is, it's legit to have mixed content in this special case. It doesn't reduce security but rather, enhance it by providing more encryption. (Here I suppose the "natural state" is when users have to use the dashboard via http.)

**Comment by proletarius101** [comment]
The API is supposed to be accessed only at 127.0.0.1, because we don't want remote control over clash, don't we?

**Comment by Dreamacro** [comment]
@proletarius101 The most useful scenario for me is LAN cross-device access, clash works on my NUC, so that I can switch proxy on my iPad or Macbook. unfortunately, LAN IP is `Mixed Content`

**Comment by proletarius101** [comment]
use httpIn that case, I agree that it could be mixed content, which is expected -- the dashboard and the api are isolated and _non-local_ from the browser's perspective. Then you can fallback to http dashboard in combine with http api, or caddy-secured https dashboard and https api. 

So this PR just adds a more secure option for the _local_ api + _non-local_ dashboard use case.

**Comment by Dreamacro** [comment]
IMO, add a `protocol` would make users confused. if you want to use `127.0.0.1` or `localhost` on HTTPS dashboard, add a separate logic is enough.

**Comment by proletarius101** [comment]
I agree that it may be confusing. But it's hard to tell whether it's https://127.0.0.1 or http://127.0.0.1 without setting it explicitly.

A not so elegant way is to always assume http connection at 127.0.0.1. If you insist, I'm ok with that.

**Comment by Dreamacro** [comment]
maybe it solved by #64

**Pull request closed without merging**
